- openmrs/apps/clinical/dashboard.json
Turn off investigation chart display on clinical dashboard.
Turn on accession table display on clinical dashboard.
> https://bahmni.atlassian.net/browse/BAH-495

- openmrs/apps/reports/reports.json
Added requiredPrivilege=”app:reports” to all reports as a default.
> BAH-395: Added requiredPrivilege tag

- openmrs/apps/appointments/printListView.html
https://bahmni.atlassian.net/browse/BAH-1036
> Siva| BAH-1036 | Update appointments print template(HTML)

- openmrs/apps/ot/app.json
New surgeryAttributes  is added to OT config., so that custom fields can be added or removed in future.
[https://bahmni.atlassian.net/browse/BAH-1059](https://bahmni.atlassian.net/browse/BAH-1059)
> Tarun, Rakesh | BAH-1059 | Config changes for Custom surgical attributes in OT

- openmrs/apps/appointments/app.json
https://bahmni.atlassian.net/browse/AP-13
> Rakesh, Supriya | AP-13 | Add default number of occurrences for recurring appointments

- openmrs/apps/clinical/dashboard.json
Changes has been added to the dashboard.json to add formsGroup. If Forms group is empty, then all forms2 forms will be pulled in.
> BAH-790|Buvaneswari|Show forms in the clinical dashboard

- openmrs/apps/home/extension.json
- openmrs/i18n/home/locale_en.json
- openmrs/migrations/addLabRoleWithPrivilege.xml
- openmrs/migrations/liquibase.xml
co-autored by Priyanka Ajmera<pajmera@thoughtworks.com>
> BAH-1497 | Add. create new lab role and map to lab-lite privilege

- openmrs/apps/home/whiteLabel.json
Jira link: https://bahmni.atlassian.net/browse/BAH-2284?atlOrigin=eyJpIjoiOGVjNmJjMjM5OWJlNDNiNDg4MjU5ZjBhNzY2NDBkMjQiLCJwIjoiaiJ9
> BAH-2284 | Add. Configuration for landing page

- .github/workflows/build_upload.yml
JIRA https://bahmni.atlassian.net/browse/BS-39
Published Images Screenshot
> BS-39 | Siva,Vijay | Publish default-config with SNOMED image tags

- .github/workflows/build_upload.yml
JIRA https://bahmni.atlassian.net/browse/BS-42
> Siva Reddy | BS-42 | deployment to SNOMED Environment

- .github/scripts/transifex.sh
- .github/workflows/build_upload.yml
Jira -> [BAH-3002](https://bahmni.atlassian.net/browse/BAH-3002)
In this PR, we have added a script that does the following :
1. Check if Transifex CLI is installed. If not installed, install the latest Transifex CLI.
2. Check if the transifex config file is present in the repo at `root/.tx/config`.
3. Push the translation source file to transifex by running `tx push -s`.
4. If a error message is thrown, capture the error.
> BAH-3002 | Add. Script To Push Translations To Transifex

- openmrs/obscalculator/BahmniObsValueCalculator.groovy
- JIRA : https://bahmni.atlassian.net/browse/BAH-3266
> BAH-3266 | Siva Reddy | Fetching concepts from default locale if no concepts in requested locale

- openmrs/apps/clinical/visit.json
- openmrs/i18n/clinical/locale_en.json
JIRA -> [BAH-3523](https://bahmni.atlassian.net/browse/BAH-3523)
> BAH-3523 | Refactor. Change Display Order of Controls in Visit Summary screen

- openmrs/apps/customDisplayControl/js/customControl.js
PR -> [BAH-3522](https://bahmni.atlassian.net/browse/BAH-3522)
This PR updates the dateTime conversion custom controller for appointments to ensure accurate display of appointment slot dateTime for all users, regardless of their client timezone.
> BAH-3522 | Fix. Timezone Difference In Appointment Schedule

- .github/scripts/transifex.sh
- .github/workflows/build_upload.yml
- .github/workflows/pull_translations.yml
This workflow is designed to retrieve translations from Transifex once every month in case resources are updated.
> BAH-3644 | Add. Workflow To Pull Translations

- openmrs/apps/customDisplayControl/js/customControl.js
JIRA -> [BAH-3714](https://bahmni.atlassian.net/browse/BAH-3714)
> BAH-3714 | Fix. Appointments List URL In Custom Control

- masterdata/configuration/liquibase/liquibase.xml
- openmrs/apps/adt/app.json
- openmrs/apps/clinical/app.json
- openmrs/apps/documentUpload/app.json
- openmrs/apps/ipd/app.json
- openmrs/apps/orders/app.json
- openmrs/apps/ot/app.json
- openmrs/apps/registration/app.json
- openmrs/i18n/registration/locale_en.json
- adds all the configurations for the pre-patient flow
JIRA Ref: 
1. [BAH-3053](https://bahmni.atlassian.net/browse/BAH-3053)
2. [BAH-3065](https://bahmni.atlassian.net/browse/BAH-3065)
> BAH-3053|Kavitha|add config for pre-patient flow

- openmrs/apps/appointments/app.json
This config change is to enable the Status option in the Add Appointment workflow.
> Phani | BAH-3010 | Enable Appointment status option ( Scheduled / Waitlist)

- openmrs/apps/adt/app.json
- openmrs/apps/clinical/app.json
- openmrs/apps/documentUpload/app.json
- openmrs/apps/ipd/app.json
- openmrs/apps/orders/app.json
- openmrs/apps/ot/app.json
JIRA - https://bahmni.atlassian.net/browse/BAH-3024
As part of this card, we are handling how columns in clinical tabular view can be hidden and how we can choose those columns that can be set as an identifier completely through configuration.
> BAH-3024 | Sort columns in the Clinical Queue tabular view

- openmrs/apps/appointments/app.json
JIRA : [BAH-3080](https://bahmni.atlassian.net/browse/BAH-3080)
> BAH-3080|add config to enable summary view

- package/docker/Dockerfile
JIRA issue Link:https://bahmni.atlassian.net/browse/BAH-3880
> BAH-3880|Deepthi M|Updated lib curl to fix High vulnerability reported in Trivy scan
